
SELECT O.ID, COALESCE(S.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA O
LEFT JOIN (SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID) S USING (ID);
