WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GEN + 1 AS GEN
    FROM ECOLI_DATA E
    JOIN ECOLI_GEN G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, G.GEN AS GENERATION
FROM ECOLI_GEN G
LEFT JOIN ECOLI_DATA E ON G.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION;