SELECT
    H.HISTORY_ID,
    FLOOR(
        C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
        * (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100)
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  USING (CAR_ID)
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
  ON D.CAR_TYPE = C.CAR_TYPE
 AND (
      (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 AND D.DURATION_TYPE = '90일 이상')
   OR (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 AND D.DURATION_TYPE = '30일 이상')
   OR (DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7  AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 AND D.DURATION_TYPE = '7일 이상')
     )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;
