-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN (
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS JULY_SUM
    FROM JULY J
    GROUP BY FLAVOR
) J
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER + J.JULY_SUM) DESC
LIMIT 3;