-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT)
FROM USED_GOODS_FILE as a
WHERE a.BOARD_ID IN (
    SELECT b.BOARD_ID
    FROM USED_GOODS_BOARD as b
    WHERE b.VIEWS = (
        SELECT MAX(VIEWS) FROM USED_GOODS_BOARD
    )
)
ORDER BY a.FILE_ID DESC;